spec:
  replicas: 10
  template:
    spec:
      volumes:
        - name: volume-mutant-detector-worker
          configMap:
            name: mutant-detector-worker-config
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /data/application.properties
          volumeMounts:
            - name: volume-mutant-detector-worker
              mountPath: /data