spec:
  replicas: 4
  template:
    spec:
      volumes:
        - name: volume-mutant-detector-worker
          configMap:
            name: mutant-detector-worker-config
      containers:
        - resources:
            limits:
              cpu: 120m
              memory: 384Mi
            requests:
              cpu: 60m
              memory: 256Mi
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /data/application.properties
          volumeMounts:
            - name: volume-mutant-detector-worker
              mountPath: /data